Adding redux to the project
kennankole/book-store-app pull request #3
Opened 2022-11-14 06:11 UTC by kennankole

* Created redux directory  
* Defined Action types in `books` and `categories`
* Created reducers in `books` and `categories`
*  Configured redux `store`
   .

2022-11-14 06:49 UTC, zieeco requested changes
Hi @kennankole,


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
_Check the comments under the review._

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-14 06:49 UTC, zieeco commented on src/redux/books/books.js
> +const REMOVEBOOK = 'REMOVE_BOOK';
- Hey, please let's improve our naming convention to follow the ducks pattern. Also, your variable is quite not easy to read. let's improve on this below:

```
const ADD_BOOK = 'bookstore/books/ADD_BOOK';
const REMOVE_BOOK = 'bookstore/books/REMOVE_BOOK';
```

2022-11-14 06:49 UTC, zieeco commented on src/redux/categories/categories.js
> +const CHECKBOOKSTATUS = 'CHECKBOOKSTATUS';
- The same issue is applicable here also:

`const CHECK_BOOK_STATUS = 'bookstore/categories/CHECK_BOOK_STATUS'`

2022-11-14 06:49 UTC, zieeco commented on src/redux/categories/categories.js
> +const CHECKBOOKSTATUS = 'CHECKBOOKSTATUS';
### Eslint-disable

[OPTIONAL]

- You should try writing codes that conform to the linter as this helps you in writing clean codes.
- Some of the errors are pretty simple to fix. Let's try improving on this as might not be marked optional in the subsequent project.

e.g: in the `categories.js` component, all you need to add is the type attribute to the button with the value of the button, as it fixes it. Please, let's kindly work on this issue(s).

2022-11-14 06:49 UTC, zieeco commented on src/redux/categories/categories.js
> +const CHECKBOOKSTATUS = 'CHECKBOOKSTATUS';
### ROUTES {Navigation.js}

- It's great how you've added those routes but you're missing the `Categries.js`. Please, kindly update this missing part of the project requirement.

2022-11-14 06:57 UTC, kennankole commented on src/redux/categories/categories.js
> +const CHECKBOOKSTATUS = 'CHECKBOOKSTATUS';
Thanks @zieeco 
I'll work on the changes.

2022-11-15 00:44 UTC, Reem-lab requested changes
# Hi @kennankole, 👋🏻👋🏻 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media2.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

 ## Highlights
- No Linters error ✅
- Descriptive PR ✅
- Great working on the Menu functionality ✅

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-15 00:44 UTC, Reem-lab commented on src/redux/books/books.js
> +const REMOVE_BOOK = 'REMOVE_BOOK';
- [ ] I think you didn't get what the previous code reviewer asked let me explain more The value of each action type needs to follow the [ducks pattern](https://github.com/erikras/ducks-modular-redux), so it will be something like:   
you can read more about duck paterrns in this link 👍🏻💯🔥🚀
> ```
> const ADD_BOOK = 'bookstore/books/ADD_BOOK';
> const REMOVE_BOOK = 'bookstore/books/REMOVE_BOOK';
> ```

2022-11-15 00:44 UTC, Reem-lab commented on src/redux/categories/categories.js
> +const CHECK_BOOK_STATUS = 'CHECK_BOOK_STATUS';
- [ ] I think you didn't get what the previous code reviewer asked let me explain more The value of each action type needs to follow the [ducks pattern](https://github.com/erikras/ducks-modular-redux), so it will be something like:   
you can read more about duck paterrns in this link 👍🏻💯🔥🚀


`const CHECK_BOOK_STATUS = 'bookstore/categories/CHECK_BOOK_STATUS'`

2022-11-15 00:58 UTC, Reem-lab approved these changes
# Hi @kennankole, 👋🏻👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🚀🔥🎉🎉 
<img src="https://media2.giphy.com/media/G7lfJRrvdhtxK8OVGy/giphy.gif"/>

## Highlights
- No Linters error ✅
- Descriptive PR ✅
- Great working on the Menu functionality and design ✅
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-15 00:59 UTC, merged