Adding redux to react components.
kennankole/book-store-app pull request #4
Opened 2022-11-16 17:30 UTC by kennankole

* Connected the app to the `redux` store
* Added all the functionalities for using `redux` in React components.

2022-11-16 18:28 UTC, OLIPLICHE requested changes
Hi @kennankole, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Use Redux store to display books👏 👏
- Add some UI elements to the components and make them *dispatch* actions👏 👏
- Linter is green (the last commit has a green check mark (✅)) 👏
- README file is descriptive 👏
- Commit messages are meaningful 👏 👏
- Gitflow is correctly used (Pull Request is made from the feature branch into the dev branch) 👏

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-16 18:28 UTC, OLIPLICHE commented on src/components/AddBook.js
> -  const { title, author, id } = props;
- Please try to fix this linter (line 8) manually don't disable it.

2022-11-16 18:28 UTC, OLIPLICHE commented on src/components/BookItem.js
>    // eslint-disable-next-line react/prop-types
- Please try to fix this linter (line 7) manually don't disable it.

2022-11-16 18:28 UTC, OLIPLICHE commented on src/components/BookItem.js
>  function BookItem(props) {
# Optional:
- I noticed that you have been using `function` in most of your component files. I would rather suggest you use ES6 class because they make your code concise and self-documenting ...

2022-11-17 01:50 UTC, emmiiorji approved these changes
Hi @kennankole, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://www.funimada.com/assets/images/cards/big/congrats-13.gif)

## Good Highlights✔

- Linter checks are passing
- Good commit messages
- Requested changes have been implememted


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-17 02:24 UTC, merged